name: Nightly E2E testing

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  e2e:
    name: E2E / Behavior tests
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
      fail-fast: false # We care about results from other pipelines

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Install cifuzz
        run: make install

      - name: Run E2E tests matrix
        run: make test/e2e
